server:
  port: 10000


#eureka:
#  instance:
#    instance-id: gateWay #主机名的修改
#    prefer-ip-address: true #显示ip,可以帮助定位问题
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/
##      ,http://localhost:8770/eureka/



spring:
  application:
    name: gateWay
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.158.135:8848
        namespace: 1594f901-f5d5-41f1-a21c-f0fba62ffe13
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true
      routes:
        - id: system # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #          uri: lb://system  #lb是loadBalance
          uri: http://localhost:9000   #匹配后提供服务的路由地址
          predicates:
            - Path=/** # 断言，路径相匹配的进行路由
  #            - Cookie=username,admin
  #        - id: state
  #          uri: lb://state
  #          predicates:
  #            - Path=/** #断言,路径相匹配的进行路由
  #            - After=2021-10-04T22:24:29.420+08:00[Asia/Shanghai] #在该时间之后访问才有效果，秒杀系统
  ##            - Cookie=username,admin #需要Cookie中有username=admin
  redis:
    host: 192.168.158.130
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000
    #连接池最大连接数（使用负值表示没有限制）
    lettuce.pool.max-active: 20
    #最大阻塞等待时间(负数表示没限制)
    lettuce.pool.max-wait: -1
    #连接池中的最大空闲连接
    lettuce.pool.max-idle: 5
    #连接池中的最小空闲连接
    lettuce.pool.min-idle: 0





