server:
  port: 9000

spring:
  redis:
    host: 192.168.158.130
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000
    #连接池最大连接数（使用负值表示没有限制）
    lettuce.pool.max-active: 20
    #最大阻塞等待时间(负数表示没限制)
    lettuce.pool.max-wait: -1
    #连接池中的最大空闲连接
    lettuce.pool.max-idle: 5
    #连接池中的最小空闲连接
    lettuce.pool.min-idle: 0
  application:
    name: system
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.158.134:3306/bill?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: psh120370
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.158.135:8848
        namespace: 1594f901-f5d5-41f1-a21c-f0fba62ffe13
#      config:
#        server-addr: 192.168.158.135:8848 #配置中心
#        namespace: 1594f901-f5d5-41f1-a21c-f0fba62ffe13
#        file-extension: yaml




mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml


#eureka:
#  instance:
#    instance-id: system #主机名的修改
#    prefer-ip-address: true #显示ip,可以帮助定位问题
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/

#eureka:
#  instance:
#    instance-id: system.one  #主机名的修改
#    prefer-ip-address: true #显示ip,可以帮助定位问题
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/,http://localhost:8770/eureka/