server:
  port: 10000


eureka:
  instance:
    instance-id: gateWay #主机名的修改
    prefer-ip-address: true #显示ip,可以帮助定位问题
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
#      ,http://localhost:8770/eureka/


spring:
  application:
    name: gateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true
      routes:
        - id: system # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
#          uri: lb://system  #lb是loadBalance
          uri: http://localhost:8050   #匹配后提供服务的路由地址
          predicates:
            - Path=/** # 断言，路径相匹配的进行路由
#            - Cookie=username,admin
#        - id: state
#          uri: lb://state
#          predicates:
#            - Path=/** #断言,路径相匹配的进行路由
#            - After=2021-10-04T22:24:29.420+08:00[Asia/Shanghai] #在该时间之后访问才有效果，秒杀系统
##            - Cookie=username,admin #需要Cookie中有username=admin

