server:
  port: 8760


eureka:
  instance:
    hostname: eureka1.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
  server:
    enable-replicated-request-compression: false
    eviction-interval-timer-in-ms: 2000

#
#eureka:
#  instance:
#    hostname: eureka1.com
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka2.com:8770/eureka/
#  server:
#    #关闭自我保护
#    enable-self-preservation: false
#    eviction-interval-time-in-ms: 2000